# Generated by Django 3.2 on 2021-04-13 15:11

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_fotky', models.CharField(blank=True, max_length=50, null=True, verbose_name='Název fotky')),
                ('popisek_fotky', models.CharField(blank=True, max_length=500, null=True, verbose_name='popisek fotky')),
                ('fotka', models.ImageField(blank=True, null=True, upload_to=cats.models.fotky, verbose_name='Fotka')),
            ],
            options={
                'ordering': ['nazev_fotky'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_druhu', models.CharField(help_text='Zadejte prosím druh kočky, popřípadě OwO pokud není známo', max_length=50, unique=True, verbose_name='Druh kočky')),
            ],
            options={
                'ordering': ['jmeno_druhu'],
            },
        ),
        migrations.CreateModel(
            name='Description_of_the_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50, verbose_name='Jméno')),
                ('vek', models.IntegerField(verbose_name='Roky Kočky')),
                ('vaha', models.IntegerField(verbose_name='Váha')),
                ('popisek', models.CharField(max_length=500, verbose_name='popisek')),
                ('species', models.ManyToManyField(help_text='Vyberte druh kočky', to='cats.Species')),
            ],
            options={
                'ordering': ['jmeno'],
            },
        ),
    ]
