# Generated by Django 3.2 on 2021-04-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description_of_the_cat',
            name='jmeno',
            field=models.CharField(blank=True, max_length=50, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='description_of_the_cat',
            name='popisek',
            field=models.CharField(blank=True, max_length=500, verbose_name='popisek'),
        ),
        migrations.AlterField(
            model_name='description_of_the_cat',
            name='vaha',
            field=models.IntegerField(blank=True, verbose_name='Váha'),
        ),
        migrations.AlterField(
            model_name='description_of_the_cat',
            name='vek',
            field=models.IntegerField(blank=True, verbose_name='Roky Kočky'),
        ),
    ]
