# Generated by Django 3.2 on 2021-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20210511_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='description_of_the_cat',
            name='fotky',
            field=models.ManyToManyField(help_text='Vyberte fotku kočky', to='cats.Photo'),
        ),
    ]
