# Generated by Django 3.2 on 2021-05-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_photo_fotka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description_of_the_cat',
            name='fotka',
        ),
    ]
