# Generated by Django 3.2 on 2021-05-12 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_auto_20210512_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description_of_the_cat',
            name='species',
        ),
        migrations.AddField(
            model_name='description_of_the_cat',
            name='druh',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cats.species'),
            preserve_default=False,
        ),
    ]
