# Generated by Django 3.2 on 2021-05-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0011_auto_20210512_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['fotka']},
        ),
    ]
