# Generated by Django 3.2 on 2021-05-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0012_alter_photo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description_of_the_cat',
            name='fotka',
            field=models.ImageField(blank=True, null=True, upload_to='cats/fotky/%Y/%m/%d/', verbose_name='Fotka'),
        ),
    ]
