# Generated by Django 3.2 on 2021-05-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0013_alter_description_of_the_cat_fotka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description_of_the_cat',
            name='fotka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cats.photo'),
            preserve_default=False,
        ),
    ]
