# Generated by Django 3.2 on 2021-05-12 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0014_alter_description_of_the_cat_fotka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description_of_the_cat',
            name='vaha',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Váha'),
        ),
        migrations.AlterField(
            model_name='description_of_the_cat',
            name='vek',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Roky Kočky'),
        ),
    ]
