# Generated by Django 3.2 on 2021-05-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0016_auto_20210512_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='fotka',
            field=models.ImageField(blank=True, null=True, upload_to='cats/fotky', verbose_name='Fotka'),
        ),
    ]
