# Generated by Django 3.2 on 2021-06-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0017_alter_photo_fotka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description_of_the_cat',
            old_name='fotka',
            new_name='foto',
        ),
    ]
